// IMPERIUM v4 — historiska ledare som kan väljas (200+). Allt är data.
// m = buff på nationsvärden medan ledaren styr. En eller två stats, 5–15.
export const LEADERS = {
  '752': [ // Sverige
    { n: 'Gustav Vasa', m: { stability: 12 } },
    { n: 'Gustav II Adolf', m: { milpower: 12, readiness: 5 } },
    { n: 'Axel Oxenstierna', m: { polpower: 12 } },
    { n: 'Birger Jarl', m: { stability: 8, safety: 5 } },
    { n: 'Karl XII', m: { milpower: 10, income: -5 } },
    { n: 'Alfred Nobel', m: { research: 12 } },
    { n: 'Dag Hammarskjöld', m: { approval: 10, justtime: 5 } },
    { n: 'Astrid Lindgren', m: { qol: 10 } },
    { n: 'Selma Lagerlöf', m: { hdi: 8 } },
    { n: 'Ingvar Kamprad', m: { income: 10 } },
  ],
  '578': [ // Norge
    { n: 'Harald Hårfagre', m: { stability: 10 } },
    { n: 'Olav den helige', m: { ideopower: 10 } },
    { n: 'Fridtjof Nansen', m: { approval: 8, research: 5 } },
    { n: 'Roald Amundsen', m: { readiness: 10 } },
    { n: 'Sigrid Undset', m: { hdi: 8 } },
  ],
  '208': [ // Danmark
    { n: 'Margareta I', m: { polpower: 12 } },
    { n: 'Christian IV', m: { factory: 8, income: 5 } },
    { n: 'H.C. Andersen', m: { qol: 10 } },
    { n: 'Niels Bohr', m: { research: 12 } },
    { n: 'Tycho Brahe', m: { research: 8 } },
  ],
  '246': [ // Finland
    { n: 'Gustaf Mannerheim', m: { milpower: 12 } },
    { n: 'Urho Kekkonen', m: { stability: 10 } },
    { n: 'Jean Sibelius', m: { approval: 8 } },
    { n: 'Linus Torvalds', m: { research: 12 } },
    { n: 'Tove Jansson', m: { qol: 10 } },
  ],
  '352': [{ n: 'Leif Eriksson', m: { readiness: 8 } }, { n: 'Snorre Sturlasson', m: { hdi: 8 } }],
  '840': [ // USA
    { n: 'George Washington', m: { stability: 12 } },
    { n: 'Abraham Lincoln', m: { freedom: 12, stability: 5 } },
    { n: 'Franklin D. Roosevelt', m: { factory: 10, approval: 5 } },
    { n: 'Theodore Roosevelt', m: { milpower: 8, qol: 5 } },
    { n: 'Dwight D. Eisenhower', m: { readiness: 10 } },
    { n: 'Martin Luther King Jr.', m: { freedom: 12 } },
    { n: 'Thomas Edison', m: { research: 10 } },
    { n: 'Benjamin Franklin', m: { polpower: 10, research: 5 } },
    { n: 'Susan B. Anthony', m: { freedom: 10 } },
  ],
  '826': [ // Storbritannien
    { n: 'Winston Churchill', m: { milpower: 10, approval: 5 } },
    { n: 'Elizabeth I', m: { stability: 10, income: 5 } },
    { n: 'Drottning Victoria', m: { income: 10, stability: 5 } },
    { n: 'Isaac Newton', m: { research: 15 } },
    { n: 'Charles Darwin', m: { research: 10 } },
    { n: 'William Shakespeare', m: { qol: 10 } },
    { n: 'Florence Nightingale', m: { hdi: 10 } },
    { n: 'Hertigen av Wellington', m: { milpower: 10 } },
  ],
  '250': [ // Frankrike
    { n: 'Napoleon Bonaparte', m: { milpower: 15, unrest: 5 } },
    { n: 'Ludvig XIV', m: { statepower: 10, income: 5 } },
    { n: 'Jeanne d’Arc', m: { readiness: 10, ideopower: 5 } },
    { n: 'Charles de Gaulle', m: { stability: 10 } },
    { n: 'Louis Pasteur', m: { research: 10, hdi: 5 } },
    { n: 'Marie Curie', m: { research: 12 } },
    { n: 'Voltaire', m: { freedom: 10 } },
  ],
  '276': [ // Tyskland
    { n: 'Otto von Bismarck', m: { polpower: 12, stability: 5 } },
    { n: 'Karl den store', m: { statepower: 10 } },
    { n: 'Johann W. von Goethe', m: { hdi: 10 } },
    { n: 'Albert Einstein', m: { research: 15 } },
    { n: 'Ludwig van Beethoven', m: { approval: 8 } },
    { n: 'Konrad Adenauer', m: { stability: 10, income: 5 } },
    { n: 'Johannes Gutenberg', m: { research: 8, hdi: 5 } },
  ],
  '380': [ // Italien
    { n: 'Julius Caesar', m: { milpower: 12, polpower: 5 } },
    { n: 'Augustus', m: { stability: 12 } },
    { n: 'Leonardo da Vinci', m: { research: 15 } },
    { n: 'Michelangelo', m: { qol: 10 } },
    { n: 'Giuseppe Garibaldi', m: { manpower: 10 } },
    { n: 'Marco Polo', m: { income: 10 } },
    { n: 'Galileo Galilei', m: { research: 10 } },
  ],
  '724': [ // Spanien
    { n: 'Isabella I', m: { stability: 10 } },
    { n: 'Karl V', m: { statepower: 10 } },
    { n: 'Miguel de Cervantes', m: { qol: 8 } },
    { n: 'El Cid', m: { milpower: 10 } },
  ],
  '620': [ // Portugal
    { n: 'Henrik Sjöfararen', m: { research: 8, income: 5 } },
    { n: 'Vasco da Gama', m: { income: 10 } },
    { n: 'Ferdinand Magellan', m: { readiness: 8 } },
  ],
  '643': [ // Ryssland
    { n: 'Peter den store', m: { factory: 10, milpower: 5 } },
    { n: 'Katarina den stora', m: { statepower: 10, hdi: 5 } },
    { n: 'Alexander Nevskij', m: { milpower: 10 } },
    { n: 'Lev Tolstoj', m: { hdi: 10 } },
    { n: 'Dmitrij Mendelejev', m: { research: 10 } },
    { n: 'Jurij Gagarin', m: { research: 8, approval: 8 } },
    { n: 'Pjotr Tjajkovskij', m: { qol: 8 } },
  ],
  '156': [ // Kina
    { n: 'Qin Shi Huang', m: { statepower: 12, unrest: 5 } },
    { n: 'Konfucius', m: { stability: 12 } },
    { n: 'Sun Tzu', m: { readiness: 12 } },
    { n: 'Zheng He', m: { income: 10 } },
    { n: 'Wu Zetian', m: { polpower: 10 } },
    { n: 'Laozi', m: { qol: 8 } },
  ],
  '392': [ // Japan
    { n: 'Oda Nobunaga', m: { milpower: 10 } },
    { n: 'Tokugawa Ieyasu', m: { stability: 12 } },
    { n: 'Kejsar Meiji', m: { factory: 10, research: 5 } },
    { n: 'Hokusai', m: { qol: 8 } },
    { n: 'Toyotomi Hideyoshi', m: { manpower: 8 } },
  ],
  '356': [ // Indien
    { n: 'Ashoka', m: { stability: 10, approval: 5 } },
    { n: 'Akbar den store', m: { integration: 10 } },
    { n: 'Mahatma Gandhi', m: { approval: 12, freedom: 5 } },
    { n: 'Chandragupta Maurya', m: { statepower: 10 } },
    { n: 'Srinivasa Ramanujan', m: { research: 12 } },
  ],
  '818': [ // Egypten
    { n: 'Ramses II', m: { milpower: 10, stability: 5 } },
    { n: 'Kleopatra', m: { polpower: 10 } },
    { n: 'Imhotep', m: { research: 10 } },
    { n: 'Gamal Abdel Nasser', m: { approval: 8, statepower: 5 } },
  ],
  '792': [ // Turkiet
    { n: 'Kemal Atatürk', m: { stability: 12, research: 5 } },
    { n: 'Süleyman den store', m: { statepower: 10, income: 5 } },
    { n: 'Mehmet II', m: { milpower: 10 } },
  ],
  '364': [ // Iran
    { n: 'Kyros den store', m: { stability: 10, freedom: 5 } },
    { n: 'Dareios I', m: { income: 10 } },
    { n: 'Avicenna', m: { research: 10, hdi: 5 } },
    { n: 'Ferdowsi', m: { ideopower: 8 } },
  ],
  '300': [ // Grekland
    { n: 'Perikles', m: { polpower: 10, freedom: 5 } },
    { n: 'Leonidas', m: { readiness: 12 } },
    { n: 'Aristoteles', m: { research: 10 } },
    { n: 'Sokrates', m: { hdi: 10 } },
    { n: 'Archimedes', m: { research: 10 } },
  ],
  '484': [ // Mexiko
    { n: 'Benito Juárez', m: { stability: 10 } },
    { n: 'Moctezuma II', m: { statepower: 8 } },
    { n: 'Frida Kahlo', m: { qol: 8 } },
    { n: 'Miguel Hidalgo', m: { freedom: 8 } },
  ],
  '076': [ // Brasilien
    { n: 'Pedro II', m: { stability: 10 } },
    { n: 'Santos-Dumont', m: { research: 10 } },
    { n: 'Pelé', m: { approval: 12 } },
  ],
  '032': [ // Argentina
    { n: 'José de San Martín', m: { milpower: 10 } },
    { n: 'Evita Perón', m: { approval: 12 } },
    { n: 'Manuel Belgrano', m: { stability: 8 } },
  ],
  '152': [{ n: 'Bernardo O’Higgins', m: { stability: 8 } }, { n: 'Gabriela Mistral', m: { hdi: 8 } }],
  '604': [{ n: 'Pachacútec', m: { statepower: 10 } }, { n: 'Túpac Amaru II', m: { freedom: 8 } }],
  '170': [{ n: 'Simón Bolívar', m: { milpower: 10, approval: 5 } }, { n: 'Gabriel García Márquez', m: { qol: 8 } }],
  '862': [{ n: 'Simón Bolívar', m: { milpower: 10, approval: 5 } }],
  '710': [ // Sydafrika
    { n: 'Nelson Mandela', m: { approval: 15, freedom: 8 } },
    { n: 'Shaka Zulu', m: { milpower: 12 } },
    { n: 'Desmond Tutu', m: { approval: 8 } },
  ],
  '231': [{ n: 'Menelik II', m: { milpower: 10 } }, { n: 'Haile Selassie', m: { stability: 8 } }, { n: 'Drottningen av Saba', m: { income: 8 } }],
  '404': [{ n: 'Jomo Kenyatta', m: { stability: 8 } }, { n: 'Wangari Maathai', m: { qol: 8 } }],
  '566': [{ n: 'Nnamdi Azikiwe', m: { stability: 8 } }, { n: 'Chinua Achebe', m: { hdi: 8 } }],
  '466': [{ n: 'Mansa Musa', m: { income: 15 } }, { n: 'Sundiata Keita', m: { stability: 10 } }],
  '616': [ // Polen
    { n: 'Nikolaus Kopernikus', m: { research: 12 } },
    { n: 'Jan III Sobieski', m: { milpower: 10 } },
    { n: 'Tadeusz Kościuszko', m: { freedom: 8 } },
    { n: 'Frédéric Chopin', m: { qol: 8 } },
  ],
  '348': [{ n: 'Stefan I', m: { stability: 10 } }, { n: 'Mátyás Corvinus', m: { research: 8 } }, { n: 'Franz Liszt', m: { qol: 8 } }],
  '203': [{ n: 'Karl IV', m: { stability: 10 } }, { n: 'Comenius', m: { hdi: 10 } }],
  '040': [{ n: 'Maria Teresia', m: { polpower: 10 } }, { n: 'W.A. Mozart', m: { approval: 10 } }, { n: 'Sigmund Freud', m: { research: 8 } }],
  '756': [{ n: 'Wilhelm Tell', m: { freedom: 10 } }, { n: 'Leonhard Euler', m: { research: 12 } }, { n: 'Henri Dunant', m: { hdi: 10 } }],
  '528': [{ n: 'Vilhelm av Oranien', m: { freedom: 10 } }, { n: 'Rembrandt', m: { qol: 8 } }, { n: 'Erasmus', m: { hdi: 10 } }, { n: 'Spinoza', m: { research: 8 } }],
  '056': [{ n: 'Gerardus Mercator', m: { research: 8 } }],
  '372': [{ n: 'Brian Boru', m: { stability: 8 } }, { n: 'Daniel O’Connell', m: { freedom: 8 } }, { n: 'James Joyce', m: { hdi: 8 } }],
  '804': [{ n: 'Bohdan Chmelnytskyj', m: { milpower: 8 } }, { n: 'Taras Sjevtjenko', m: { ideopower: 8 } }],
  '100': [{ n: 'Simeon den store', m: { statepower: 8 } }],
  '642': [{ n: 'Stefan den store', m: { milpower: 8 } }, { n: 'Vlad III', m: { safety: 8, approval: -5 } }],
  '688': [{ n: 'Nikola Tesla', m: { research: 15 } }, { n: 'Stefan Dušan', m: { statepower: 8 } }],
  '191': [{ n: 'Ruđer Bošković', m: { research: 8 } }],
  '807': [{ n: 'Moder Teresa', m: { approval: 12 } }],
  '008': [{ n: 'Skanderbeg', m: { milpower: 10 } }],
  '376': [{ n: 'Kung David', m: { stability: 10 } }, { n: 'Kung Salomo', m: { income: 10 } }, { n: 'Golda Meir', m: { polpower: 10 } }, { n: 'David Ben-Gurion', m: { stability: 8 } }],
  '682': [{ n: 'Ibn Saud', m: { stability: 10 } }],
  '368': [{ n: 'Hammurabi', m: { stability: 12 } }, { n: 'Harun al-Rashid', m: { income: 8, research: 5 } }, { n: 'Nebukadnessar II', m: { statepower: 8 } }],
  '760': [{ n: 'Zenobia', m: { polpower: 10 } }],
  '788': [{ n: 'Hannibal Barkas', m: { milpower: 12 } }],
  '504': [{ n: 'Ibn Battuta', m: { income: 8 } }],
  '012': [{ n: 'Massinissa', m: { readiness: 8 } }],
  '586': [{ n: 'Muhammad Ali Jinnah', m: { stability: 8 } }],
  '050': [{ n: 'Mujibur Rahman', m: { approval: 8 } }],
  '764': [{ n: 'Chulalongkorn', m: { stability: 10 } }],
  '704': [{ n: 'Trần Hưng Đạo', m: { readiness: 12 } }, { n: 'Systrarna Trưng', m: { manpower: 8 } }],
  '360': [{ n: 'Sukarno', m: { stability: 8 } }, { n: 'Gajah Mada', m: { statepower: 8 } }],
  '608': [{ n: 'José Rizal', m: { freedom: 8, hdi: 5 } }],
  '410': [{ n: 'Sejong den store', m: { research: 12, hdi: 5 } }, { n: 'Yi Sun-sin', m: { milpower: 12 } }],
  '496': [{ n: 'Djingis khan', m: { milpower: 15, unrest: 5 } }, { n: 'Kublai khan', m: { statepower: 10 } }],
  '398': [{ n: 'Abai Qunanbajuly', m: { hdi: 8 } }],
  '860': [{ n: 'Timur Lenk', m: { milpower: 12 } }, { n: 'Ulugh Beg', m: { research: 10 } }, { n: 'al-Khwarizmi', m: { research: 12 } }],
  '124': [{ n: 'Frederick Banting', m: { research: 10, hdi: 5 } }, { n: 'Terry Fox', m: { approval: 10 } }],
  '036': [{ n: 'Howard Florey', m: { research: 10 } }],
  '554': [{ n: 'Edmund Hillary', m: { readiness: 8, approval: 5 } }, { n: 'Ernest Rutherford', m: { research: 12 } }],
  '068': [{ n: 'Túpac Katari', m: { freedom: 8 } }],
  '858': [{ n: 'José Artigas', m: { freedom: 8 } }],
  '218': [{ n: 'Eugenio Espejo', m: { hdi: 8 } }],
  '512': [{ n: 'Ahmad bin Said', m: { income: 8 } }],
  '887': [{ n: 'Drottning Arwa', m: { stability: 8 } }],
  '458': [{ n: 'Parameswara', m: { income: 8 } }],
  '112': [{ n: 'Frantsisk Skaryna', m: { hdi: 8 } }],
  '440': [{ n: 'Gediminas', m: { statepower: 8 } }],
  '428': [{ n: 'Krišjānis Barons', m: { hdi: 8 } }],
  '233': [{ n: 'Lennart Meri', m: { approval: 8 } }],
  '705': [{ n: 'Primož Trubar', m: { hdi: 8 } }],
  '703': [{ n: 'Ľudovít Štúr', m: { ideopower: 8 } }],
  '270': [{ n: 'Kunta Kinteh', m: { freedom: 8 } }],
  '288': [{ n: 'Kwame Nkrumah', m: { stability: 8 } }],
  '686': [{ n: 'Léopold Senghor', m: { hdi: 8 } }],
  '834': [{ n: 'Julius Nyerere', m: { stability: 8 } }],
  '716': [{ n: 'Nehanda Nyakasikana', m: { ideopower: 8 } }],
  '024': [{ n: 'Drottning Nzinga', m: { milpower: 10 } }],
  '180': [{ n: 'Patrice Lumumba', m: { freedom: 8 } }],
  '324': [{ n: 'Samori Touré', m: { milpower: 8 } }],
};

// arketyper för länder utan kurerad lista — alltid någon att välja
export const GENERIC_LEADERS = [
  { n: 'Den store reformatorn', m: { polpower: 10 } },
  { n: 'Järnkanslern', m: { statepower: 10 } },
  { n: 'Folkhjälten', m: { approval: 10 } },
  { n: 'Fältmarskalken', m: { milpower: 10 } },
  { n: 'Handelsfursten', m: { income: 10 } },
  { n: 'Vetenskapsministern', m: { research: 10 } },
  { n: 'Fredsmäklaren', m: { justtime: 8, approval: 5 } },
  { n: 'Industrialisten', m: { factory: 10 } },
  { n: 'Folkbildaren', m: { hdi: 10 } },
  { n: 'Enaren', m: { stability: 10 } },
  { n: 'Frihetskämpen', m: { freedom: 10 } },
  { n: 'Välfärdsarkitekten', m: { welfare: 10, qol: 5 } },
  { n: 'Spionmästaren', m: { safety: 10 } },
  { n: 'Ungdomens röst', m: { approval: 8, research: 5 } },
  { n: 'Den gamla räven', m: { polpower: 8, corruption: 5 } },
  { n: 'Generalen', m: { readiness: 10 } },
  { n: 'Diplomaten', m: { justtime: 10 } },
  { n: 'Bankiren', m: { income: 8, gdp: 5 } },
  { n: 'Agitatorn', m: { ideopower: 10, unrest: 3 } },
  { n: 'Byggmästaren', m: { factory: 8, qol: 5 } },
];

export function pickLeader(cid) {
  const pool = LEADERS[String(cid)];
  if (pool && Math.random() < 0.8) return pool[Math.floor(Math.random() * pool.length)];
  return GENERIC_LEADERS[Math.floor(Math.random() * GENERIC_LEADERS.length)];
}

export function leaderDesc(l) {
  return Object.entries(l.m).map(([k, v]) => `${k.toUpperCase()} ${v > 0 ? '+' : ''}${v}`).join(', ');
}